### PR TITLE
/beta/index.html Update

### PR DESCRIPTION
**Pull request by 12vanblart**
Updated /beta/index.html and /beta/global/global.css files to utilize CSS grid & a mobile first design pattern to improve readability and clean up code. 

_These changes are to be reviewed in /beta. Once reviewed, a new PR will merge changes to live._

### CODE REVIEW

**Comment by alexmiddeleer** [comment]
Pretty huge diff! Thanks for all the hard work. In the future, if possible, please submit a different PR for automated tool changes, so it's easier to review the stuff that matters.

Did anyone discuss dropping internet explorer support, since CSS grid is not supported by IE?

**Comment by 12vanblart** [comment]
There should be any changes to anything outside of index.html (if there were I can separate out the css to a new file for `index.html` instead of using the same style sheet). 

As for ie support, if everything looks okay, I can add the ie supported prefixes to the classes.

**Comment by alexmiddeleer** [comment]
I personally don't think we need IE support since I would think very few of our users are still on IE, but might want to ask @PapaCapricorn to confirm since it's ultimately his decision.

**Comment by 12vanblart** [comment]
Looking through, I do see that at some point I removed the margin-left from `#shiftstoned-heading`. This should be re-added and addressed within the context of the index.html file rather than global.css. 

Also, apologies for the global.css diff. Prettier sure had an opinion about the formatting.

**Comment by alexmiddeleer** [comment]
By the way, the conflicts are likely due to me syncing the beta/index.html with the latest /index.html. I'm guessing maybe @PapaCapricorn added some new stuff before you finished work on this branch.

**Comment by PapaCapricorn** [comment]
Thanks for working on this guys. I'm not sure what the next steps are, but I'm ok with not supporting IE. Previously we had discussed the option of including a dialog for IE users, something to the effect of "Please upgrade to a browser that doesn't suck."

**Comment by alexmiddeleer** [comment]
@12vanblart Let me know if you need any help resolving conflicts.

**Comment by 12vanblart** [comment]
@alexmiddeleer I think I got it (and if not, that's why I'm in the /beta folder 😉 )

Papa sent me some minor formatting changes to make before merging, so I'll add another comment when those are addressed.

**Comment by 12vanblart** [comment]
@PapaCapricorn I added the padding so that the image's top will align with the Heading text's top. 

Going to work on the layout guide and send it to you on Discord next!

**Comment by 12vanblart** [comment]
As a follow-up to my previous comment, the style guide can be found here: https://docs.google.com/document/d/1gbORKr7VveRGhCFBpYGAwpfJaz-asoo0zmU4alCUMQc/edit?usp=sharing 

and should be available to anyone interested.

**Pull request merged**
